.env:
  prefix: ""

server:
  port: 0

eureka:
  client:
    service-url:
      defautlZone: http://eureka:password@localhost:8761/eureka

spring:
  flyway:
    baselineOnMigrate: true
    url: ${MAIL_SENDER_POSTGRESQL_CONNECTION}
    user: ${MAIL_SENDER_POSTGRESQL_USERNAME}
    password: ${MAIL_SENDER_POSTGRESQL_PASSWORD}
  application:
    name: mail-sender-service
  datasource:
    url: ${MAIL_SENDER_POSTGRESQL_CONNECTION}
    username: ${MAIL_SENDER_POSTGRESQL_USERNAME}
    password: ${MAIL_SENDER_POSTGRESQL_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SENDER_MAIL_USERNAME}
    password: ${MAIL_SENDER_MAIL_PASSWORD}
    properties:
      smtp:
        auth: true
        starttls:
          enable: true

  kafka:
    topic:
      name: mail-sender-topic
    consumer:
      bootstrap-servers: localhost:9092
      group-id: mail-sender
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.trusted.packages: "*"
#  spring.mail.host=smtp.gmail.com
#  spring.mail.port=587
#  spring.mail.username=${MAIL_SENDER_MAIL_USERNAME}
#  spring.mail.password=${MAIL_SENDER_MAIL_PASSWORD}
#  spring.mail.properties.mail.smtp.auth=true

#  spring.mail.properties.mail.smtp.starttls.enable=true