.env:
  prefix: ""

mail-sender-url: http://mail-sender-service/api/v1/email/send

server:
  port: 0
authentication:
  auth:
    tokenSecret: ${TOKEN_SECRET}
    tokenExpirationMsec: ${TOKEN_EXPIRATION_MSEC}
    refreshTokenExpirationMsec: ${REFRESH_TOKEN_EXPIRATION_MSEC}
    accessTokenCookieName: accessToken
    refreshTokenCookieName: refreshToken
eureka:
  client:
    service-url:
      defautlZone: http://eureka:password@localhost:8761/eureka

spring:
  kafka:
    topic:
      name: mail-sender-topic
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: auth-user-service
  datasource:
    url: ${AUTH_SERVICE_POSTGRESQL_CONNECTION}
    username: ${AUTH_SERVICE_POSTGRESQL_USERNAME}
    password: ${AUTH_SERVICE_POSTGRESQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update