.env:
  prefix: ""

management:
  endpoints:
    jmx:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE}

authentication:
  auth:
    tokenSecret: myTokenSecret
    tokenExpirationMsec: 3600000 #1 hour
    refreshTokenExpirationMsec: 7776000000 #90 days
    accessTokenCookieName: accessToken
    refreshTokenCookieName: refreshToken

spring:
  cloud: 
    compatibility-verifier:
      enabled: false
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  # mvc:
  #   pathmatch:
  #     matching-strategy: ant-path-matcher
  application:
    name: swot-analysis-service

  data:
    mongodb:
      uri: ${API_CORE_MONGO_CONNECTION}
  web:
    locale: en

  jackson:
    serialization:
      write-dates-as-timestamps: false
server:
  port: 0

# springdoc:
#   swagger-ui:
#     path: /swot/api-docs/swagger-ui.html
